openapi: 3.2.0
info:
  title: Federation of Agricultural Collectivities - API
  description:
    API for managing the Federation of Agricultural Collectivities in Madagascar.
    This file contains the endpoints related to the admission, transfer and resignation of members 
    within an agricultural collectivity (Part B).
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /member:
    post:
      tags:
        - Member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./openapi.yml#/components/schemas/Member"
      responses:
        201:
          description: New member added successfully
          content:
            application/json:
              schema:
                $ref: "./openapi.yml#/components/schemas/Member"
        400:
          description: All conditions are not met(first name, last name, address, etc. may be missing)
          content:
            text/plain:
              schema:
                type: string
              example: Bad request
  
