openapi: 3.2.0
info:
  title: Federation of Agricultural Collectivities - API
  description:
    This file contains the endpoints related to member contributions, membership fees
    and payments to the collectivity, as well as the percentage of periodic contributions
    transferred to the national federation (Part C).
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /collectivities/{id}/membership-fee:
    post:
      tags:
        - Contribution
      parameters:
        $ref: "./openapi.yml#/components/parameters/CollectivityIdPathVariable"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./openapi.yml#/components/schemas/MembershipFee"
      responses:
        201:
          description: Membership fee registered successfully
          content:
            application/json:
              schema:
                $ref: "./openapi.yml#/components/schemas/MembershipFee"
        400:
          description: All conditions are not met
          content:
            text/plain:
              schema:
                type: string
              example: Bad request
